import { expect, fixture, html } from '@open-wc/testing';
import { getShadowPart } from '../../test-utils.js';
import './define-disclosure-badge.js';
import type { LoquixDisclosureBadge } from './loquix-disclosure-badge.js';

describe('loquix-disclosure-badge', () => {
  it('renders default "Generated by AI" text', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge></loquix-disclosure-badge>`,
    );
    const badge = getShadowPart(el, 'badge');
    expect(badge).to.exist;
    expect(badge!.textContent).to.contain('Generated by AI');
    expect(badge!.getAttribute('role')).to.equal('note');
  });

  it('uses custom agent-name', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge agent-name="Claude"></loquix-disclosure-badge>`,
    );
    expect(el.agentName).to.equal('Claude');
    const badge = getShadowPart(el, 'badge')!;
    expect(badge.textContent).to.contain('Generated by Claude');
  });

  it('reflects action property to text', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge
        action="summarized"
        agent-name="Claude"
      ></loquix-disclosure-badge>`,
    );
    expect(el.action).to.equal('summarized');
    const badge = getShadowPart(el, 'badge')!;
    expect(badge.textContent).to.contain('Summarized by Claude');
  });

  it('handles all action verbs', async () => {
    const actions = [
      { action: 'generated', expected: 'Generated by' },
      { action: 'summarized', expected: 'Summarized by' },
      { action: 'rewrote', expected: 'Rewritten by' },
      { action: 'suggested', expected: 'Suggested by' },
    ] as const;

    for (const { action, expected } of actions) {
      const el = await fixture<LoquixDisclosureBadge>(
        html`<loquix-disclosure-badge action="${action}"></loquix-disclosure-badge>`,
      );
      const badge = getShadowPart(el, 'badge')!;
      expect(badge.textContent).to.contain(expected);
    }
  });

  it('all 4 action values render correct localized text with agentName', async () => {
    const cases = [
      { action: 'generated', expected: 'Generated by Claude' },
      { action: 'summarized', expected: 'Summarized by Claude' },
      { action: 'rewrote', expected: 'Rewritten by Claude' },
      { action: 'suggested', expected: 'Suggested by Claude' },
    ] as const;

    for (const { action, expected } of cases) {
      const el = await fixture<LoquixDisclosureBadge>(
        html`<loquix-disclosure-badge
          action="${action}"
          agent-name="Claude"
        ></loquix-disclosure-badge>`,
      );
      const badge = getShadowPart(el, 'badge')!;
      expect(badge.textContent).to.contain(expected);
    }
  });

  it('invalid/unknown action defaults to "generated"', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge agent-name="Bot"></loquix-disclosure-badge>`,
    );
    // Force an unknown action value
    (el as any).action = 'unknown_action' as any;
    await el.updateComplete;
    const badge = getShadowPart(el, 'badge')!;
    expect(badge.textContent).to.contain('Generated by Bot');
  });

  it('empty agentName still renders without error', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge agent-name=""></loquix-disclosure-badge>`,
    );
    expect(el).to.exist;
    const badge = getShadowPart(el, 'badge')!;
    expect(badge.textContent).to.contain('Generated by');
  });

  it('variant property reflects to DOM', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge variant="label"></loquix-disclosure-badge>`,
    );
    expect(el.getAttribute('variant')).to.equal('label');
    el.variant = 'inline';
    await el.updateComplete;
    expect(el.getAttribute('variant')).to.equal('inline');
  });

  it('CSS part "badge" is queryable', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge></loquix-disclosure-badge>`,
    );
    const badge = getShadowPart(el, 'badge');
    expect(badge).to.exist;
    expect(badge!.tagName.toLowerCase()).to.equal('span');
  });

  it('icon SVG has aria-hidden="true"', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge></loquix-disclosure-badge>`,
    );
    const icon = el.shadowRoot!.querySelector('.icon');
    expect(icon).to.exist;
    expect(icon!.getAttribute('aria-hidden')).to.equal('true');
  });

  it('star icon SVG path is present', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge></loquix-disclosure-badge>`,
    );
    const svg = el.shadowRoot!.querySelector('.icon svg');
    expect(svg).to.exist;
    const path = svg!.querySelector('path');
    expect(path).to.exist;
    expect(path!.getAttribute('d')).to.include('M12 2');
  });

  it('action property reflects to DOM', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge action="summarized"></loquix-disclosure-badge>`,
    );
    expect(el.getAttribute('action')).to.equal('summarized');
  });

  it('agent-name attribute reflects to DOM', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge agent-name="GPT"></loquix-disclosure-badge>`,
    );
    expect(el.getAttribute('agent-name')).to.equal('GPT');
  });

  it('aria-label on badge matches rendered text', async () => {
    const el = await fixture<LoquixDisclosureBadge>(
      html`<loquix-disclosure-badge
        action="suggested"
        agent-name="Claude"
      ></loquix-disclosure-badge>`,
    );
    const badge = getShadowPart(el, 'badge')!;
    expect(badge.getAttribute('aria-label')).to.equal('Suggested by Claude');
  });
});
